def funt(n):
    try:
        if n==2:
            return "Ok"
    except Exception as e:
        return str(e)
    

print(funt("sa"))


{
    'status':200,
    'message':'success'
    'data'
}